import {
  LayoutGrid,
  Building2,
  FileText,
  Search,
  Map,
  Bell,
  Settings as SettingsIcon,
  Moon,
  Plus,
  Menu,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Eye,
  Pencil,
  ShieldCheck,
  ChevronDown,
  Printer,
  CheckCircle,
  Download,
  RefreshCw,
  Circle,
  ClipboardList,
  Flag,
  User,
  Users,
  BarChart3,
  Plug,
  Shield,
  Lock,
  LogOut,
  Laptop2,
  Mail,
  MessageSquare,
  CreditCard,
  UserPlus,
  Trash2,
  BadgeCheck,
} from 'lucide-react';

const ICONS = {
  dashboard: LayoutGrid,
  establishments: Building2,
  permits: FileText,
  inspections: Search,
  map: Map,
  notifications: Bell,
  settings: SettingsIcon,
  search: Search,
  moon: Moon,
  plus: Plus,
  menu: Menu,
  check: CheckCircle2,
  warning: AlertTriangle,
  close: XCircle,
  eye: Eye,
  edit: Pencil,
  shield: ShieldCheck,
  chevronDown: ChevronDown,
  print: Printer,
  checkCircle: CheckCircle,
  download: Download,
  refresh: RefreshCw,
  clipboard: ClipboardList,
  flag: Flag,
  file: FileText,
  user: User,
  users: Users,
  reports: BarChart3,
  integrations: Plug,
  security: Shield,
  lock: Lock,
  logout: LogOut,
  device: Laptop2,
  mail: Mail,
  sms: MessageSquare,
  payment: CreditCard,
  invite: UserPlus,
  trash: Trash2,
  healthCard: BadgeCheck,
};

export default function Icon({ name, size = 16, color = '#1F2430', className = '' }) {
  const Cmp = ICONS[name] || Circle;
  return <Cmp size={size} color={color} className={className} strokeWidth={2} />;
}
